Adjusting identation and fixing program. It was not compiling due to the following errors
 Menu_nota git:(master) gcc MENU_NOTA.c
MENU_NOTA.c:163:99: error: expected ';' after expression
    printf("Sera necessario fazer a prova do Grau C, Digite 0 para informar a nota do Grau C: \n"):
                                                                                                  ^
                                                                                                  ;
MENU_NOTA.c:187:53: error: expected ';' after expression
    if(notaGrauc*0.70)+(notaTrabalhograuA*0.30) >= 6
                                                    ^
                                                    ;
MENU_NOTA.c:187:49: warning: relational comparison result unused [-Wunused-comparison]
    if(notaGrauc*0.70)+(notaTrabalhograuA*0.30) >= 6
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
MENU_NOTA.c:189:56: error: expected ';' after expression
        printf("Va beber, Digite 0 para continuar: \n"):
                                                       ^
                                                       ;
MENU_NOTA.c:199:1: error: void function 'menu' should not return a value [-Wreturn-type]
return 0;
^      ~
MENU_NOTA.c:208:25: error: expected ';' at end of declaration
       char substituicao
                        ^
                        ;
1 warning and 5 errors generated.
➜  Menu_nota git:(master) gcc MENU_NOTA.c
MENU_NOTA.c:123:108: error: expected ';' after expression
            printf("Sera necessario fazer a prova do Grau C, Digite 0 para informar a nota do Grau C: \n") : scanf("%d", &continuar);
                                                                                                           ^
                                                                                                           ;
1 error generated.